# @package _global_

run_type: "val"
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234
cuda: True

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'
checkpoint_save_path: 'checkpoints/'
checkpoint_load_path: baselines/CVRP/DACT/DACT/pretrained/cvrp100-epoch-198.pt

data_file_path: data/CVRP/cvrp${graph_size}/data_test_seed234_size1000_${coords_dist}.pt
generator_args: {}
dataset_size: 1000
batch_size: 8
strict_max_num: False
