# @package _global_

run_type: "val"
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'

env_cfg:
  data_file_path: data/CVRP/cvrp${graph_size}/data_test_seed234_size1000_${coords_dist}.pt
dataset_size: 1000 #512
batch_size: 1 #8 #32      # number of envs
eval_metric_key: 'rew'
render: False      # requires batch_size = 1
monitor_cfg: {}
strict_max_num: False
