# @package _global_
# policy config

policy: "TS"

policy_cfg:
  first_solutions_strategy: 'PATH_CHEAPEST_ARC' # 'SAVINGS' #
  local_search_strategy: 'TABU_SEARCH'
  time_limit: #2
  solution_limit: #None
  verbose: False
  log_search: False
