##############################################################################
###                         Data generation                                ###
##############################################################################

# (R) [str] Type of your scheduling problem - this template is for jssp
sp_type: jssp
# (O)   [string]  Filename under the generated data will be saved (subdirectory is chosen by sp_type)
instances_file: config_job_task3_tools_test_5000.pkl
# (O)   [int]     Seed for all pseudo random generators (random, numpy, torch)
seed: 0
# (R) [int] Number of jobs to be scheduled
num_jobs: 6
# (R) [int] Number of tasks per job to be scheduled (has to be equal to num_machines for jssp)
num_tasks: 6
# (R) [int] Number of available machines (has to be equal to num_tasks for jssp)
num_machines: 6
# (O) [int] Number of available tools to be scheduled
num_tools: 0
# (O) [list[int]] Duration of tasks are samples uniformly from this list
runtimes: [2, 4, 6, 8, 10]
# (R) [int] Number of instances (instances of the scheduling problem) to be generated
num_instances: 5000
# (O) [int] Number of parallel processes used to calculate the instances
num_processes: 16
# (O) [bool] Save the generated data in a file
write_to_file: True
