# @package _global_
# model parameters

model: "FF_flat_flat"

model_cfg:
  embedding_dim: 128

  # encoder
  # ==============================================
  encoder_args:
    node_encoder_type: "FFNodeEncoder"
    node_encoder_cfg:
      hidden_dim: 128
      num_layers: 2
      activation: "gelu"
      skip: True
      norm_type: "ln"
      dropout: 0.25

    sol_encoder_type: "FlatSolEncoder"
    sol_encoder_cfg:
      hidden_dim: 128
      num_layers: 1
      propagate_best: False

  # aggregator
  # ==============================================
  aggregator_args:
    components: [ "node_feature_emb", "current_sol_emb" ]
    pooling: [ "mean", "mean" ]
    combination: "cat"

  # decoder
  # ==============================================
  decoder_type: "FFDecoder"
  decoder_args:
    hidden_dim: 128
    num_layers: 2
    activation: "gelu"

