# @package _global_
# problem args

problem: "jssp"
num_jobs: 30
num_machines: 15
duration_dist: 'uniform'

# general VecEnv cfg
env_cfg:
  share_memory: False
  fixed_dataset: True
  create_nbh_graph: False

# JSSP Env cfg
env_kwargs:
  generator_args: {}
  sampling_args:
    sample_size: 1024
    num_jobs: ${num_jobs}
    num_machines: ${num_machines}
