# @package _global_

run_type: "val"
debug_lvl: 0  # 0 disables debugging and verbosity completely, >1 activates additional debugging functionality
global_seed: 1234

# global paths and logging
log_lvl: INFO
tb_log_path: 'logs/tb/'
log_path: 'logs/'

data_file_path: data/JSSP/jssp${num_jobs}x${num_machines}/data_val_seed123_size512_${duration_dist}.pt
generator_args: {}
dataset_size: 512
batch_size: 8 #32      # number of workers
