# @package _global_

has_overrides: True

model_cfg:
  encoder_args:
    sol_encoder_type: #
    sol_encoder_cfg: #

  aggregator_args:
    components: [ "node_feature_emb", "meta_feature_emb" ]
    pooling: [ "mean", "none" ]
    combination: "cat"
