# @package _global_

env_kwargs:
  num_steps: 100
  acceptance_mode: 'SELECT_EPSILON'
  operator_mode: 'SET'
  position_mode: 'ALL'
  construction_args:
    method: 'FDD_MWKR'
  mode_args:
    search_criterion: 'best'
    selection_criterion: 'sampling'
    ls_ops: ['CEI']
    random_shuffle: True
    num_nodes_per_iter: 2
    epsilon: 0.1
    restart_at_step: 15
    restart_mode: "initial"
