# @package _global_

env_kwargs:
  num_steps: 100
  acceptance_mode: 'SELECT_EPSILON'
  operator_mode: 'SET'
  position_mode: 'ALL'
  construction_args:
    method: 'FDD_MWKR'
  mode_args:
    search_criterion: 'best'
    selection_criterion: 'sampling'
    ls_ops: ['CET']
    random_shuffle: False
    num_nodes_per_iter: 1
    epsilon: 0.05
    restart_at_step: 8
    restart_mode: "perturb"
    restart_args:
      iters: 3